// Copyright © 2026 BxKangKi. Licensed under the MIT License.

#pragma once

#include "CoreMinimal.h"
#include "Styling/SlateColor.h"
#include "UI/StartWorldWidget.h"
#include "WorldSelectionWidget.generated.h"

class UButton;
class UPanelWidget;
class UTextBlock;
class UWorldSelectionWidget;

/** Internal click dispatcher used by generated UButton entries in UWorldSelectionWidget. */
UCLASS()
class GLTFSIMULATOR_API UWorldSelectionButtonClickHandler : public UObject
{
    GENERATED_BODY()

public:
    void Setup(UWorldSelectionWidget* InOwnerWidget, const FString& InWorldFolderName);

    UFUNCTION()
    void HandleClicked();

private:
    TWeakObjectPtr<UWorldSelectionWidget> OwnerWidget;
    FString WorldFolderName;
};

/**
 * World-selection menu widget used as the parent class for WBP_LevelMenu.
 *
 * Assign WorldListPanel in WBP_LevelMenu. This class creates a native UButton + UTextBlock for
 * every world folder passed by AStartActor and opens the selected world through the referenced
 * StartActor after null checking. No separate button widget class, native-event override,
 * or widget-name search is required.
 */
UCLASS(Blueprintable, BlueprintType)
class GLTFSIMULATOR_API UWorldSelectionWidget : public UStartWorldWidget
{
    GENERATED_BODY()

public:
    virtual void NativeConstruct() override;
    virtual void NativeDestruct() override;
    virtual void SetWorldSelectionData(const TMap<FString, FString>& Values) override;

    /** Assigns the panel that receives generated world buttons. Rebuilds the list immediately when data already exists. */
    UFUNCTION(BlueprintCallable, Category="Start World|World Selection")
    void SetWorldListPanel(UPanelWidget* InWorldListPanel);

    /** Rebuilds the generated button list from GetFolderNameMap(). */
    UFUNCTION(BlueprintCallable, Category="Start World|World Selection")
    void RebuildWorldButtons();

    /** Removes only the buttons generated by this native widget. */
    UFUNCTION(BlueprintCallable, Category="Start World|World Selection")
    void ClearWorldButtons();

protected:
    /** Panel that receives generated world buttons. Assign this variable in WBP_LevelMenu. */
    UPROPERTY(BlueprintReadWrite, meta=(BindWidgetOptional), Category="Start World|Widgets")
    TObjectPtr<UPanelWidget> WorldListPanel;

    /** Padding applied inside each generated button around its text block. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Start World|Generated Buttons")
    FMargin GeneratedButtonTextPadding = FMargin(12.0f, 6.0f);

    /** Text color for generated button labels. Use foreground by default so it follows the active button style. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Start World|Generated Buttons")
    FSlateColor GeneratedButtonTextColor = FSlateColor::UseForeground();

private:
    UButton* CreateWorldButton(const FString& WorldFolderName, const FString& DisplayName);

    UPROPERTY(Transient)
    TArray<TObjectPtr<UButton>> GeneratedWorldButtons;

    UPROPERTY(Transient)
    TArray<TObjectPtr<UWorldSelectionButtonClickHandler>> GeneratedClickHandlers;
};
