// Copyright © 2026 BxKangKi. Licensed under the MIT License.

/**
 * @file WorldSelectionWidget.h
 * Role: Defines this source unit's responsibility within glTFSimulator.
 * USelectionWidgetBase owns generated WBP entry creation and lifetime behavior.
 */

#pragma once

#include "CoreMinimal.h"
#include "UI/StartWorldWidget.h"
#include "WorldSelectionWidget.generated.h"

class UPanelWidget;

/**
 * World-selection menu. UStartWorldWidget provides world-opening behavior and inherits the common
 * generated selection-entry implementation from USelectionWidgetBase.
 */
UCLASS(Blueprintable, BlueprintType)
class GLTFSIMULATOR_API UWorldSelectionWidget : public UStartWorldWidget
{
    GENERATED_BODY()

public:
    virtual void NativeConstruct() override;
    virtual void SetWorldSelectionData(const TMap<FString, FString>& Values) override;

    /** Assigns the panel that receives generated world buttons and rebuilds the list. */
    UFUNCTION(BlueprintCallable, Category="Start World|World Selection")
    void SetWorldListPanel(UPanelWidget* InWorldListPanel);

    /** Rebuilds the generated button list from GetFolderNameMap(). */
    UFUNCTION(BlueprintCallable, Category="Start World|World Selection")
    void RebuildWorldButtons();

    /** Removes only entries generated by this native widget. */
    UFUNCTION(BlueprintCallable, Category="Start World|World Selection")
    void ClearWorldButtons();

protected:
    virtual void OnSelectionEntryActivated(const FString& SelectionKey) override;
};
